"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const stack_1 = require("./lib/stack");
const user_1 = require("./lib/user");
const names = new stack_1.Stack();
names.push('Anna');
names.push('Maria');
names.push('John');
console.log(`size of stack: ${names.size()}`);
console.log(`${names.pop()}`);
console.log(`${names.pop()}`);
console.log(`size of stack: ${names.size()}`);
const users = new stack_1.Stack();
users.push(new user_1.User('Anna', 'Smith'));
users.push(new user_1.User('Maria', 'Anders'));
users.push(new user_1.User('John', 'Doe'));
console.log(`number of users:${users.size()}`);
const u = users.pop();
u.show();
